function jlang(str) {
    return jlocalized[str];
}

var jlocalized={
    'InitialLat' : 55.658996,
    'InitialLng' : 12.579346,
    'clickToReport' : 'click to report this marker as invalid',
    'clickToEdit' : 'click to edit this marker',
    'clickToDelete' : 'click to delete this marker',
    'clickToBook' : 'click to mark as occupied',
    'clickToSave' : 'click to save',
    'bookedUntil' : 'marked occupied until',
    'markerInfoTitle' : 'Title',
    'markerInfoGoalsize' : 'Goalsize',
    'markerInfoFieldsize' : 'Fieldsize',
    'markerInfoFundament' : 'Fundament',
    'markerInfoExtra' : 'Extra',
    'markerInfoFacilities' : 'Facilities',
    'fundamentGrass' : 'Grass',
    'fundamentGrowel' : 'Growel',
    'fundamentConcrete' : 'Concrete',
    'fundamentDirt' : 'Dirt',
    'fundamentAsphalt' : 'Asphalt',
    'fundamentIndoor' : 'Indoor',
    'fundamentHardwood' : 'Hardwood',
    'fundamentTurf' : 'Turf',
    'facilityWaterpost' : 'Waterpost',
    'facilityToilet' : 'Toilet',
    'facilityBench' : 'Bench',
    'facilityFence' : 'Fence',
    'RatingCancel' : 'Cancel Rating',
    'RatingGiveIt' : 'Give it',
    'Yes' : 'Yes',
    'No' : 'No',
    'Name' : 'Name',
    'Email' : 'Email',
    'yourFeedback' : 'Your Feedback',
    'Send' : 'Send',
    'Message' : 'Message',
    'Subject' : 'A Feedback Message',
    'recievedMsg' : 'Thank you for your message',
    'notRecivedMsg' : 'Sorry but your message could not be sent, please try again later',
    'disclaimer' : 'Please feel free to get in touch, we value your feedback',
    'occupied' : 'Marked as occupied until',
    'searchHint' : 'Search',
    'unknown' : 'Unknown',
    'all' : 'All',
    'clear' : 'Clear'
};
